function [handles, plotMe] = plotEyelidTracesFromDuringPhase_PCP2ChR2Pilot(eyelidTrace, expMice, contMice, ...
    expPhaseDays, contPhaseDays, timeVector, meanOrMed, phaseName, legendLabels)

% plot mean eyelid traces with normalized y axis: during
handles.duringNorm = figure;
subplot(1,2,1)
xlabelstring = 'time(s)';
ylabelstring = 'normalized FEC-baaseline';
titlestring = ['experimental: ', phaseName];
[plotMe.norm.exp] = plotEyelidTraces(eyelidTrace.during.mean, eyelidTrace.during.mouse, expMice.names, ...
    expPhaseDays, timeVector, ...
    'not individ means', 'group means', 'normalize', meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
thisMax = max(max(plotMe.norm.exp(:,40:85)));
ylim([-0.02 thisMax*1.1])
xlim([0 0.25])
subplot(1,2,2)
titlestring = ['control: ', phaseName];
[plotMe.norm.cont] = plotEyelidTraces(eyelidTrace.during.mean, eyelidTrace.during.mouse, contMice.names, ...
    contPhaseDays, timeVector, ...
    'not individ means', 'group means', 'normalize',meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
thatMax = max(max(plotMe.norm.cont(:,40:85)));
if thisMax >= thatMax
    ylim([-0.02 thisMax*1.1])
    xlim([0 0.25])
else
    ylim([-0.02 thatMax*1.1])
    xlim([0 0.25])
    subplot(1,2,1)
    ylim([-0.02 thatMax*1.1])
end

% plot mean eyelid traces with normal y-axis: during
handles.during = figure;
subplot(1,2,1)
xlabelstring = 'time(s)';
ylabelstring = 'FEC-baseline';
titlestring = ['experimental: ', phaseName];
[plotMe.exp] = plotEyelidTraces(eyelidTrace.during.mean, eyelidTrace.during.mouse, expMice.names, ...
    expPhaseDays, timeVector, ...
    'not individ means', 'group means', 'do not normalize',meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
ylim([-0.02 0.8])
xlim([0 0.25])
subplot(1,2,2)
titlestring = ['control: ', phaseName];
[plotMe.cont] = plotEyelidTraces(eyelidTrace.during.mean, eyelidTrace.during.mouse, contMice.names, ...
    contPhaseDays, timeVector, ...
    'not individ means', 'group means', 'do not normalize',meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
ylim([-0.02 0.8])
xlim([0 0.25])

% plot mean hit eyelid traces: during
handles.duringHit = figure;
subplot(1,2,1)
xlabelstring = 'time(s)';
ylabelstring = 'FEC-baseline';
titlestring = ['experimental: ', phaseName, ': hits'];
[plotMe.hit.exp] = plotEyelidTraces(eyelidTrace.during.hitmean, eyelidTrace.during.mouse, expMice.names, ...
    expPhaseDays, timeVector, ...
    'not individ means', 'group means', 'do not normalize',meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
ylim([-0.02 0.8])
xlim([0 0.25])
subplot(1,2,2)
titlestring = ['control: ', phaseName, ': hits'];
[plotMe.hit.cont] = plotEyelidTraces(eyelidTrace.during.hitmean, eyelidTrace.during.mouse, contMice.names, ...
    contPhaseDays, timeVector, ...
    'not individ means', 'group means', 'do not normalize',meanOrMed,...
    legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
    'same figure');
ylim([-0.02 0.8])
xlim([0 0.25])

% % plot mean miss eyelid traces (misses just anything that is not a hit, not
% % the manually scored misses): during
% handles.duringMiss = figure;
% subplot(1,2,1)
% xlabelstring = 'time(s)';
% ylabelstring = 'FEC-baseline';
% titlestring = ['experimental: ', phaseName, ': misses'];
% [plotMe] = plotEyelidTraces(eyelidTrace.during.missmean, eyelidTrace.during.mouse, expMice.names, ...
%     expPhaseDays, timeVector, ...
%     'not individ means', 'group means', 'do not normalize',meanOrMed,...
%     legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
%     'same figure');
% ylim([-0.02 0.8])
% xlim([0 0.25])
% subplot(1,2,2)
% titlestring = ['control: ', phaseName, ': misses'];
% [plotMe] = plotEyelidTraces(eyelidTrace.during.missmean, eyelidTrace.during.mouse, contMice.names, ...
%     contPhaseDays, timeVector, ...
%     'not individ means', 'group means', 'do not normalize',meanOrMed,...
%     legendLabels, titlestring, xlabelstring, ylabelstring, [0 0 0; 1 0 1; 0 1 0; 0 0 1],...
%     'same figure');
% ylim([-0.02 0.8])
% xlim([0 0.25])
end